// Interface automatically generated by schemas-to-ts

import { Article } from "./Article";
import { Article_Plain } from "./Article";
import { Seo, Seo_NoRelations, Seo_Plain } from "./Seo";
export interface BlogHomePage {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    seo?: Seo;
    featuredArticle?: { data: Article };
    locale: string;
    localizations?: { data: BlogHomePage[] };
  };
}
export interface BlogHomePage_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  seo?: Seo_Plain
  featuredArticle?: Article_Plain;
  locale: string;
  localizations?: BlogHomePage_Plain[];
}

export interface BlogHomePage_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  featuredArticle?: number;
  seo?: Seo_NoRelations;
  locale: string;
  localizations?: BlogHomePage[];
}
